### ISSUE TITLE
Automatic setup of not yet existent dictionaries

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-entity-search-api#21]
Automatic setup of not yet existent dictionaries by adding entities to dictionaries so we do not have to setup new dictionaries by Open Semantic Search Apps anymore and API users have not to add dictionaries before use manually by dictionary manager.

**Comment by Mandalka** [comment]
Dictionary will be autogenerated by Dictionary Manager if adding first entity to it by Entity Manager.
