### ISSUE TITLE
Switch aliases/synonyms to case insensitive by default

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-entity-search-api#27]
Switch generated Solr aliases/synonyms config to case insensitive and bidirectional by default

**Comment by Mandalka** [comment]
Synonyms/aliases by Entity Manager now bidirectional.

**Comment by Mandalka** [comment]
Is not case sensitive anymore since https://github.com/opensemanticsearch/solr.deb/commit/132548060bac259a8225be3cad9c6817921c922e

If using former installation, just switch that parameter "ignoreCase" to true in var/solr/data/opensemanticsearch/conf/_schema_analysis_synonyms_skos.json
