### ISSUE TITLE
Migrate entity extraction from KeepWordFilterFactory to Solr Tagger

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-entity-search-api#31]
With the new https://lucene.apache.org/solr/guide/7_4/the-tagger-handler.html we can integrate entity extraction with stemming at ETL time and need not to temporary index the document and to manage an additional dictionary file anymore with need of core reloads, since all in Solr index and updateable by Solr API.

**Comment by Mandalka** [comment]
Migrated to Solr Text Tagger, so no additional management of dictionary plain text files additionally to Solr entities index anymore.
