### ISSUE TITLE
Stemming for entity extraction

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-entity-search-api#34]
(Optional) integration of stemming for dictionary/ontology/thesaurus based entity extraction

**Comment by Mandalka** [comment]
Added hunspell rules and dictionaries to Solr config for named entities index / core.

**Comment by Mandalka** [comment]
Implemented export of optional stemming fields from ontologies / SKOS thesaurus from configuration of stemming options in Open Semantic Search Apps in Ontologies manager for each ontology and in Solr Ontology Tagger which exports them to entities index.

Todo: Configuration of the stemmer analyzers in Solr entities core out of the box.

**Comment by Mandalka** [comment]
Entity extraction / entity linking now support multiple taggers / analyzers / stemmers.

**Comment by YoannMR** [comment]
That sounds great!

@Mandalka  Could you please give an example of how it differs from previous entity linking? What does "multiple taggers" mean? What type of taggers are there?

**Comment by Mandalka** [comment]
The previous entity extraction was done by shingling tokens of the full text while temporary indexing to a solr core and use a keepwordfactory with a (therefore generated) plaintext list with the entities labels.

With the new Solr Text Tagger matching/extracting entities can by done without temporary indexing as document by the new tagger request handler and using optimized data structures in entity index which now can be fully configured by REST-API / standard Solr data posts instead using/managing additional plain text files for matching. This index is more powerful than keepwordfactory, for example the matching with full text can use more Solr analyzers like stemmers and has optimized data strucutres for matching (FST).

So Tagger mean a Solr Text Tagger, which extracts entities by matching entities from a field in entities index with the full text. Multiple taggers are used for example, if multiple stemmers like Porter and Hunspell stemmer are configured for the ontology or thesaurus, so we can use multiple / different index fields which can have different/multiple analyzer/stemmer settings.

**Comment by YoannMR** [comment]
@Mandalka thanks a lot for your detailed answer!

**Comment by Mandalka** [comment]
Implemented automatic config of stemming in ETL plugin for entity extraction by ontologies settings in Ontology Manager web UI.

**Comment by Mandalka** [comment]
Preconfigured some stemmers in Solr core for entities index. Using them by ETL plugin for named entity extraction can be activated for SKOS thesaurus or ontology by web config ui in Ontologies Manager.
