### ISSUE TITLE
Synonyms to bidirectional

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-entity-search-api#37]
Synonym graph config to bidirectional, so search with alias(es) will find preferred label, too.

**Comment by Mandalka** [comment]
Synonyms / aliases of entities added by entity manager (f.e. internal thesaurus app of Open Semantic Search Apps) will be added bidirectional, too like on import of external thesauri or ontologies by Solr Ontology Tagger.
