### ISSUE TITLE
Running in docker

### ISSUE THREAD

**Issue by Johanvdberg** [opensemanticsearch/open-semantic-entity-search-api#45]
Hallo

I want to use docker to run the search engine on windows. I did run `docker pull opensemanticsearch/solr` but do not know how to do "Call shell script build-deb" to build the dependencies.

When run  `docker run  -p 8983:8983 opensemanticsearch/solr` i can access teh service thought "http://localhost:8983/" but I expected a search interface but see the solr Admin console.

How do run semantic search using docker instead of using virtual box?

**Comment by Mandalka** [comment]
Work on Docker containers in https://github.com/opensemanticsearch/open-semantic-search/issues/390 - with next release maybe end of the year there will be admin documentation for the Docker images in /docs too.
